### ISSUE TITLE
CT error: Cannot read property 'lazyLink' of undefined

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#120]
This started on 5/30/18 @ 3:49PM:

equality-explorer : fuzz : require.js : load
Uncaught TypeError: Cannot read property 'lazyLink' of undefined
TypeError: Cannot read property 'lazyLink' of undefined
    at BasicsScreen.EqualityExplorerScreen [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1527716950478/equality-explorer/js/common/EqualityExplorerScreen.js?bust=1527718836657:30:31)
    at new BasicsScreen (https://bayes.colorado.edu/continuous-testing/snapshot-1527716950478/equality-explorer/js/basics/BasicsScreen.js?bust=1527718836657:38:28)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1527716950478/equality-explorer/js/equality-explorer-main.js?bust=1527718836657:28:7
    at window.phetLaunchSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1527716950478/joist/js/SimLauncher.js?bust=1527718836657:44:11)
    at doneLoadingImages (https://bayes.colorado.edu/continuous-testing/snapshot-1527716950478/joist/js/SimLauncher.js?bust=1527718836657:65:18)
    at Object.launch (https://bayes.colorado.edu/continuous-testing/snapshot-1527716950478/joist/js/SimLauncher.js?bust=1527718836657:119:9)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1527716950478/equality-explorer/js/equality-explorer-main.js?bust=1527718836657:24:15
    at Object.execCb (https://bayes.colorado.edu/continuous-testing/snapshot-1527716950478/sherpa/lib/require-2.1.11.js:1650:25)
    at Module.check (https://bayes.colorado.edu/continuous-testing/snapshot-1527716950478/sherpa/lib/require-2.1.11.js:866:35)
    at Module.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1527716950478/sherpa/lib/require-2.1.11.js:1113:20)
Approximately 5/30/2018, 3:49:10 PM

**Comment by pixelzoom** [comment]
This was broken by https://github.com/phetsims/joist/commit/69e76f81a0003f9cd8672dc6ad0b9f0ef3be277d, where Screen `screenActiveProperty` was renamed to `activeProperty` by @zepumph.  This Property is public and used by Equality Explorer.

**Comment by pixelzoom** [comment]
Renamed to `activeProperty` in Equality Explorer. Closing.
