### ISSUE TITLE
CT attempt to access positiveLocation before it was initialized

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/equality-explorer#149]
This same error is in basics and two variables as well
```
equality-explorer : fuzz : require.js : load
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: attempt to access positiveLocation before it was initialized
Error: Assertion failed: attempt to access positiveLocation before it was initialized
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/assert/js/assert.js:22:13)
    at ObjectTermCreator.get positiveLocation [as positiveLocation] (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548935463063:177:17)
    at ObjectTermCreator.manageTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548935463063:310:37)
    at ObjectTermCreator.createTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548935463063:287:12)
    at TermCreatorNode.addInputListener.SimpleDragHandler.createForwardingListener.allowTouchSnag (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/view/TermCreatorNode.js?bust=1548935463063:53:21)
    at Object.down (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/SimpleDragHandler.js?bust=1548935463063:448:13)
    at Object.touchmove (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/SimpleDragHandler.js?bust=1548935463063:455:42)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548935463063:1748:35)
    at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548935463063:1787:14)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548935463063:1717:12)
id: Bayes Chrome
Approximately 1/31/2019, 3:42:42 AM
equality-explorer : fuzz : require.js : load
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: attempt to access positiveLocation before it was initialized
Error: Assertion failed: attempt to access positiveLocation before it was initialized
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/assert/js/assert.js:22:13)
    at ObjectTermCreator.get positiveLocation [as positiveLocation] (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548935463063:177:17)
    at ObjectTermCreator.manageTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548935463063:310:37)
    at ObjectTermCreator.createTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548935463063:287:12)
    at TermCreatorNode.addInputListener.SimpleDragHandler.createForwardingListener.allowTouchSnag (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/view/TermCreatorNode.js?bust=1548935463063:53:21)
    at Object.down (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/SimpleDragHandler.js?bust=1548935463063:448:13)
    at Object.touchenter (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/SimpleDragHandler.js?bust=1548935463063:452:42)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548935463063:1748:35)
    at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548935463063:1787:14)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548935463063:1717:12)
id: Bayes Chrome
Approximately 1/31/2019, 3:42:42 AM
equality-explorer : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: attempt to access positiveLocation before it was initialized
Error: Assertion failed: attempt to access positiveLocation before it was initialized
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/assert/js/assert.js:22:13)
    at ObjectTermCreator.get positiveLocation [as positiveLocation] (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548935463063:177:17)
    at ObjectTermCreator.manageTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548935463063:310:37)
    at ObjectTermCreator.createTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548935463063:287:12)
    at TermCreatorNode.addInputListener.SimpleDragHandler.createForwardingListener.allowTouchSnag (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/view/TermCreatorNode.js?bust=1548935463063:53:21)
    at Object.down (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/SimpleDragHandler.js?bust=1548935463063:448:13)
    at Object.touchmove (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/SimpleDragHandler.js?bust=1548935463063:455:42)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548935463063:1748:35)
    at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548935463063:1787:14)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548935463063:1717:12)
id: Bayes Chrome
Approximately 1/31/2019, 3:42:42 AM
equality-explorer : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: attempt to access positiveLocation before it was initialized
Error: Assertion failed: attempt to access positiveLocation before it was initialized
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/assert/js/assert.js:22:13)
    at ObjectTermCreator.get positiveLocation [as positiveLocation] (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548935463063:177:17)
    at ObjectTermCreator.manageTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548935463063:310:37)
    at ObjectTermCreator.createTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548935463063:287:12)
    at TermCreatorNode.addInputListener.SimpleDragHandler.createForwardingListener.allowTouchSnag (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/view/TermCreatorNode.js?bust=1548935463063:53:21)
    at Object.down (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/SimpleDragHandler.js?bust=1548935463063:448:13)
    at Object.touchenter (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/SimpleDragHandler.js?bust=1548935463063:452:42)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548935463063:1748:35)
    at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548935463063:1787:14)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548935463063:1717:12)
id: Bayes Chrome
Approximately 1/31/2019, 3:42:42 AM
equality-explorer : fuzz : require.js-canvas : load
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: attempt to access positiveLocation before it was initialized
Error: Assertion failed: attempt to access positiveLocation before it was initialized
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/assert/js/assert.js:22:13)
    at VariableTermCreator.get positiveLocation [as positiveLocation] (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548936757295:177:17)
    at VariableTermCreator.manageTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548936757295:310:37)
    at VariableTermCreator.createTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548936757295:287:12)
    at TermCreatorNode.addInputListener.SimpleDragHandler.createForwardingListener.allowTouchSnag (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/view/TermCreatorNode.js?bust=1548936757295:53:21)
    at Object.down (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/SimpleDragHandler.js?bust=1548936757295:448:13)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548936757295:1757:27)
    at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548936757295:1787:14)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548936757295:1717:12)
    at Input.downEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548936757295:1531:12)
id: Bayes Chrome
Approximately 1/31/2019, 3:42:42 AM
equality-explorer : fuzz : require.js-canvas : load
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: attempt to access positiveLocation before it was initialized
Error: Assertion failed: attempt to access positiveLocation before it was initialized
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/assert/js/assert.js:22:13)
    at VariableTermCreator.get positiveLocation [as positiveLocation] (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548936757295:177:17)
    at VariableTermCreator.manageTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548936757295:310:37)
    at VariableTermCreator.createTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548936757295:287:12)
    at TermCreatorNode.addInputListener.SimpleDragHandler.createForwardingListener.allowTouchSnag (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/view/TermCreatorNode.js?bust=1548936757295:53:21)
    at Object.down (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/SimpleDragHandler.js?bust=1548936757295:448:13)
    at Object.touchenter (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/SimpleDragHandler.js?bust=1548936757295:452:42)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548936757295:1748:35)
    at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548936757295:1787:14)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548936757295:1717:12)
id: Bayes Chrome
Approximately 1/31/2019, 3:42:42 AM
equality-explorer : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: attempt to access positiveLocation before it was initialized
Error: Assertion failed: attempt to access positiveLocation before it was initialized
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/assert/js/assert.js:22:13)
    at VariableTermCreator.get positiveLocation [as positiveLocation] (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548936757295:177:17)
    at VariableTermCreator.manageTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548936757295:310:37)
    at VariableTermCreator.createTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548936757295:287:12)
    at TermCreatorNode.addInputListener.SimpleDragHandler.createForwardingListener.allowTouchSnag (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/view/TermCreatorNode.js?bust=1548936757295:53:21)
    at Object.down (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/SimpleDragHandler.js?bust=1548936757295:448:13)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548936757295:1757:27)
    at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548936757295:1787:14)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548936757295:1717:12)
    at Input.downEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548936757295:1531:12)
id: Bayes Chrome
Approximately 1/31/2019, 3:42:42 AM
equality-explorer : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: attempt to access positiveLocation before it was initialized
Error: Assertion failed: attempt to access positiveLocation before it was initialized
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/assert/js/assert.js:22:13)
    at VariableTermCreator.get positiveLocation [as positiveLocation] (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548936757295:177:17)
    at VariableTermCreator.manageTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548936757295:310:37)
    at VariableTermCreator.createTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/model/TermCreator.js?bust=1548936757295:287:12)
    at TermCreatorNode.addInputListener.SimpleDragHandler.createForwardingListener.allowTouchSnag (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/equality-explorer/js/common/view/TermCreatorNode.js?bust=1548936757295:53:21)
    at Object.down (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/SimpleDragHandler.js?bust=1548936757295:448:13)
    at Object.touchenter (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/SimpleDragHandler.js?bust=1548936757295:452:42)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548936757295:1748:35)
    at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548936757295:1787:14)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1548931362258/scenery/js/input/Input.js?bust=1548936757295:1717:12)
id: Bayes Chrome
Approximately 1/31/2019, 3:42:42 AM
```

**Comment by pixelzoom** [comment]
@samreid This started immediately after switching to `endedSimConstructionEmitter` in #148.  I will be switching back to `frameStartedEmitter`.

**Comment by pixelzoom** [comment]
I reverted #148.   I'll watch CT to verify that this issue goes away.

**Comment by pixelzoom** [comment]
CT has been through 4 cycles without a problem, so I'll close this issue.
