### ISSUE TITLE
CT cannot read property 'count' of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/equality-explorer#155]
Also in EEB and EETV
```
equality-explorer : fuzz : built : run
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'count' of undefined
TypeError: Cannot read property 'count' of undefined
    at m (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/build/phet/equality-explorer_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1158:181345)
    at i.value (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/build/phet/equality-explorer_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1158:180125)
    at t.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/build/phet/equality-explorer_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1158:628547)
    at t.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/build/phet/equality-explorer_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1158:645884)
    at t.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/build/phet/equality-explorer_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1158:939465)
    at t.disposeTermNode (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/build/phet/equality-explorer_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1158:943264)
    at t.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/build/phet/equality-explorer_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1158:943669)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/build/phet/equality-explorer_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1158:1097994
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/build/phet/equality-explorer_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1158:165426)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/build/phet/equality-explorer_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1158:182818
id: Bayes Chrome
Approximately 8/1/2019, 7:04:58 PM
equality-explorer : fuzz : built : run
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'count' of undefined
TypeError: Cannot read property 'count' of undefined
    at m (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/build/phet/equality-explorer_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1158:181345)
    at i.value (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/build/phet/equality-explorer_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1158:180125)
    at t.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/build/phet/equality-explorer_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1158:628547)
    at t.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/build/phet/equality-explorer_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1158:645884)
    at t.disposeTermNode (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/build/phet/equality-explorer_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1158:943264)
    at t.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/build/phet/equality-explorer_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1158:943669)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/build/phet/equality-explorer_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1158:1097994
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/build/phet/equality-explorer_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1158:165426)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/build/phet/equality-explorer_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1158:182818
    at n.value (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/build/phet/equality-explorer_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1158:180417)
id: Bayes Chrome
Approximately 8/1/2019, 7:04:58 PM
equality-explorer : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: type name key is not in cache: ActionIO.Vector2IO
Error: Assertion failed: type name key is not in cache: ActionIO.Vector2IO
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/assert/js/assert.js:22:13)
    at removeActionIOFromCache (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/axon/js/Action.js?:303:15)
    at Action.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/axon/js/Action.js?:223:7)
    at Action.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/tandem/js/PhetioObject.js?:141:22)
    at SeparateTermsDragListener.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/scenery/js/input/SimpleDragHandler.js?:414:28)
    at SeparateTermsDragListener.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/js/common/view/TermDragListener.js?:139:43)
    at SeparateTermsDragListener.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/js/common/view/SeparateTermsDragListener.js?:70:42)
    at SeparateTermsDragListener.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/tandem/js/PhetioObject.js?:141:22)
    at ObjectTermNode.TermNode.disposeTermNode (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/js/common/view/TermNode.js?:144:29)
    at ObjectTermNode.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/js/common/view/TermNode.js?:157:12)
id: Bayes Chrome
Approximately 8/1/2019, 7:04:58 PM
equality-explorer : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: type name key is not in cache: ActionIO.Vector2IO
Error: Assertion failed: type name key is not in cache: ActionIO.Vector2IO
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/assert/js/assert.js:22:13)
    at removeActionIOFromCache (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/axon/js/Action.js?:303:15)
    at Action.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/axon/js/Action.js?:223:7)
    at Action.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/tandem/js/PhetioObject.js?:141:22)
    at CombineTermsDragListener.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/scenery/js/input/SimpleDragHandler.js?:414:28)
    at CombineTermsDragListener.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/js/common/view/TermDragListener.js?:139:43)
    at CombineTermsDragListener.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/tandem/js/PhetioObject.js?:141:22)
    at VariableTermNode.TermNode.disposeTermNode (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/js/common/view/TermNode.js?:144:29)
    at VariableTermNode.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/js/common/view/TermNode.js?:157:12)
    at VariableTermNode.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/tandem/js/PhetioObject.js?:141:22)
id: Bayes Chrome
Approximately 8/1/2019, 7:04:58 PM
equality-explorer : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: type name key is not in cache: ActionIO.Vector2IO
Error: Assertion failed: type name key is not in cache: ActionIO.Vector2IO
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/assert/js/assert.js:22:13)
    at removeActionIOFromCache (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/axon/js/Action.js?:303:15)
    at Action.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/axon/js/Action.js?:223:7)
    at Action.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/tandem/js/PhetioObject.js?:141:22)
    at CombineTermsDragListener.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/scenery/js/input/SimpleDragHandler.js?:414:28)
    at CombineTermsDragListener.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/js/common/view/TermDragListener.js?:139:43)
    at CombineTermsDragListener.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/tandem/js/PhetioObject.js?:141:22)
    at ConstantTermNode.TermNode.disposeTermNode (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/js/common/view/TermNode.js?:144:29)
    at ConstantTermNode.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/js/common/view/TermNode.js?:157:12)
    at ConstantTermNode.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/tandem/js/PhetioObject.js?:141:22)
id: Bayes Chrome
Approximately 8/1/2019, 7:04:58 PM
equality-explorer : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: type name key is not in cache: ActionIO.Vector2IO
Error: Assertion failed: type name key is not in cache: ActionIO.Vector2IO
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/assert/js/assert.js:22:13)
    at removeActionIOFromCache (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/axon/js/Action.js?:303:15)
    at Action.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/axon/js/Action.js?:223:7)
    at Action.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/tandem/js/PhetioObject.js?:141:22)
    at SeparateTermsDragListener.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/scenery/js/input/SimpleDragHandler.js?:414:28)
    at SeparateTermsDragListener.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/js/common/view/TermDragListener.js?:139:43)
    at SeparateTermsDragListener.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/js/common/view/SeparateTermsDragListener.js?:70:42)
    at SeparateTermsDragListener.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/tandem/js/PhetioObject.js?:141:22)
    at ConstantTermNode.TermNode.disposeTermNode (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/js/common/view/TermNode.js?:144:29)
    at ConstantTermNode.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1564707898905/equality-explorer/js/common/view/TermNode.js?:157:12)
id: Bayes Chrome
Approximately 8/1/2019, 7:04:58 PM
```

**Comment by pixelzoom** [comment]
This is related to ActionIO:

```js
Uncaught Error: Assertion failed: type name key is not in cache: ActionIO.Vector2IO
```

@zepumph @samreid have been working on this, so looping them in here to review.

**Comment by zepumph** [comment]
Fixed above, see https://github.com/phetsims/equality-explorer/issues/155. Closing
