### ISSUE TITLE
CT: nextOperandIndex out of range: 41

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#160]
This assertion failure occurred once in CT, but is worthy of investigation, with low priority:

```
equality-explorer : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604510742286/equality-explorer/equality-explorer_en.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1604510742286%22%2C%22timestamp%22%3A1604512142831%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: nextOperandIndex out of range: 41
Error: Assertion failed: nextOperandIndex out of range: 41
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604510742286/assert/js/assert.js:22:13)
at Object.incrementFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604510742286/equality-explorer/js/common/view/UniversalOperationControl.js:141:21)
at fire (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604510742286/equality-explorer/js/common/view/ObjectPicker.js:248:31)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604510742286/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604510742286/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604510742286/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604510742286/axon/js/Emitter.js:60:19)
at ObjectPickerInputListener.fire (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604510742286/scenery/js/listeners/FireListener.js:99:23)
at CallbackTimer.fire (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604510742286/axon/js/CallbackTimer.js:106:25)
at CallbackTimer.stop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604510742286/axon/js/CallbackTimer.js:78:14)
id: Bayes Chrome
Snapshot from 11/4/2020, 10:25:42 AM
```

**Comment by pixelzoom** [comment]
Steps to reproduce manually:

1. Run the sim unbuilt with ?ea
2. Go to the "Solve It!" screen
3. Select Level 1
4. Press and hold the up arrow on the ObjectPicker for the operand. When it hits the max, it will fail with this assertion:

```
assert.js:22 Uncaught Error: Assertion failed: value failed isValidValue: 41
    at window.assertions.assertFunction (assert.js:22)
    at Object.isValueValid (ValidatorDef.js:307)
    at validate (validate.js:25)
    at NumberProperty.validateNumberProperty (NumberProperty.js:105)
    at NumberProperty.js:138
    at TinyEmitter.emit (TinyEmitter.js:71)
    at NumberProperty._notifyListeners (Property.js:280)
    at NumberProperty.set (Property.js:178)
    at NumberProperty.set value [as value] (Property.js:350)
    at fire (ObjectPicker.js:252)
```

If you press and hold the down-arrow on the ObjectPicker, when it hits the min it will fail with:

```
assert.js:22 Uncaught Error: Assertion failed: value failed isValidValue: -1
    at window.assertions.assertFunction (assert.js:22)
    at Object.isValueValid (ValidatorDef.js:307)
    at validate (validate.js:25)
    at NumberProperty.validateNumberProperty (NumberProperty.js:105)
    at NumberProperty.js:138
    at TinyEmitter.emit (TinyEmitter.js:71)
    at NumberProperty._notifyListeners (Property.js:280)
    at NumberProperty.set (Property.js:178)
    at NumberProperty.set value [as value] (Property.js:350)
    at fire (ObjectPicker.js:265)
```

**Comment by pixelzoom** [comment]
This appears to be a problem with ObjectPicker.  The same error occurs if you increment/decrement by pressing once for each value (instead of press-and-hold).  When you get to the max or min, even though the arrow appears to be disabled, you can still click.  It also occurs with the ObjectPickers in the Operations screen.

The most likely candidate for this regression is https://github.com/phetsims/equality-explorer/commit/5409983b1c650c883c9503224d86ac9e34795ce2, which involved replacing deprecated listeners in ObjectPicker, and bringing it forward to match NumberPicker.

**Comment by pixelzoom** [comment]
Fixed in the above commit.  Verified manually and with `?screens=4&ea&fuzz` in working copy.  I'll leave this open for a few CT cycles.

**Comment by pixelzoom** [comment]
Looks good in CT, closing.
