### ISSUE TITLE
CT cannot read property x of null

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/equality-explorer#161]
Happening in Basics and Two Variables as well
```
equality-explorer : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1604652787156%22%2C%22timestamp%22%3A1604671819661%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'x' of null
TypeError: Cannot read property 'x' of null
at AV.getEquivalentTermPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1604652787156%22%2C%22timestamp%22%3A1604671819661%7D&fuzz&memoryLimit=1000:864:1017669)
at a (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1604652787156%22%2C%22timestamp%22%3A1604671819661%7D&fuzz&memoryLimit=1000:864:1021680)
at a.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1604652787156%22%2C%22timestamp%22%3A1604671819661%7D&fuzz&memoryLimit=1000:864:37999)
at qb._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1604652787156%22%2C%22timestamp%22%3A1604671819661%7D&fuzz&memoryLimit=1000:864:62692)
at qb.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1604652787156%22%2C%22timestamp%22%3A1604671819661%7D&fuzz&memoryLimit=1000:864:62068)
at mV.moveTo (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1604652787156%22%2C%22timestamp%22%3A1604671819661%7D&fuzz&memoryLimit=1000:864:1013777)
at Ob.start (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1604652787156%22%2C%22timestamp%22%3A1604671819661%7D&fuzz&memoryLimit=1000:864:1022540)
at start (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1604652787156%22%2C%22timestamp%22%3A1604671819661%7D&fuzz&memoryLimit=1000:864:1021226)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1604652787156%22%2C%22timestamp%22%3A1604671819661%7D&fuzz&memoryLimit=1000:864:1008095
at X.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1604652787156%22%2C%22timestamp%22%3A1604671819661%7D&fuzz&memoryLimit=1000:864:53456)
id: Bayes Chrome
Snapshot from 11/6/2020, 1:53:07 AM

----------------------------------

equality-explorer : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/equality-explorer_en.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1604652787156%22%2C%22timestamp%22%3A1604657443655%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: attempt to access positivePosition before it was initialized
Error: Assertion failed: attempt to access positivePosition before it was initialized
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/assert/js/assert.js:22:13)
at ObjectTermCreator.get positivePosition [as positivePosition] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/js/common/model/TermCreator.js:174:15)
at ObjectTermCreator.manageTerm (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/js/common/model/TermCreator.js:307:35)
at ObjectTermCreator.createTerm (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/js/common/model/TermCreator.js:284:10)
at TermCreatorNode.addInputListener.SimpleDragHandler.createForwardingListener.allowTouchSnag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/js/common/view/TermCreatorNode.js:49:21)
at Object.down (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/scenery/js/input/SimpleDragHandler.js:476:11)
at Object.touchmove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/scenery/js/input/SimpleDragHandler.js:483:40)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/scenery/js/input/Input.js:1813:33)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/scenery/js/input/Input.js:1854:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/scenery/js/input/Input.js:1780:10)
id: Bayes Chrome
Snapshot from 11/6/2020, 1:53:07 AM

----------------------------------

equality-explorer : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/equality-explorer_en.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1604652787156%22%2C%22timestamp%22%3A1604662580716%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: attempt to access positivePosition before it was initialized
Error: Assertion failed: attempt to access positivePosition before it was initialized
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/assert/js/assert.js:22:13)
at ConstantTermCreator.get positivePosition [as positivePosition] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/js/common/model/TermCreator.js:174:15)
at ConstantTermCreator.manageTerm (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/js/common/model/TermCreator.js:307:35)
at ConstantTermCreator.createTerm (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/js/common/model/TermCreator.js:284:10)
at TermCreatorNode.addInputListener.SimpleDragHandler.createForwardingListener.allowTouchSnag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/equality-explorer/js/common/view/TermCreatorNode.js:49:21)
at Object.down (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/scenery/js/input/SimpleDragHandler.js:476:11)
at Object.touchenter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/scenery/js/input/SimpleDragHandler.js:480:40)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/scenery/js/input/Input.js:1813:33)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/scenery/js/input/Input.js:1854:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/scenery/js/input/Input.js:1780:10)
id: Bayes Chrome
Snapshot from 11/6/2020, 1:53:07 AM
```

**Comment by pixelzoom** [comment]
This error started occurring 11/5/202 at 4:43PM.  It's occurring consistently.  And it is immediately reproducible with unbuilt fuzz testing in my working copy.   The most recent changes in equality-explorer where some class renames on 10/27/2020, so I suspect this regression is due to common code changes.

**Comment by zepumph** [comment]
The ordering of input fuzzing changed over in https://github.com/phetsims/phet-io-wrappers/issues/371. This was done after discussion with @jonathanolson and @samreid. Input fuzzing is no longer part of the stepSimulation() function, but happens before. This seems to be the cause of this issue. Adding myself as an assignee.

**Comment by zepumph** [comment]
This bad workaround fixes the error and confirms that it is from the first fuzz, which occurs before any stepSimulation has occurred:

```diff
Index: js/Sim.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/Sim.js	(revision 6bedf42da927e9db66ed9680b98ce3a8e7d01f38)
+++ js/Sim.js	(date 1604686358470)
@@ -887,7 +887,7 @@
               // http://paulirish.com/2011/requestanimationframe-for-smart-animating/
               // Launch the bound version so it can easily be swapped out for debugging.
               // Schedules animation updates and runs the first step()
-              this.boundRunAnimationLoop();
+              this.boundRunAnimationLoop(false);
 
               // If the sim is in playback mode, then flush the timer's listeners. This makes sure that anything kicked
               // to the next frame with `timer.runOnNextTick` during startup (like every notification about a PhET-iO
@@ -939,7 +939,7 @@
   }
 
   // @private - Bound to this.boundRunAnimationLoop so it can be run in window.requestAnimationFrame
-  runAnimationLoop() {
+  runAnimationLoop(fuzz=true) {
     if ( !this.destroyed ) {
       window.requestAnimationFrame( this.boundRunAnimationLoop );
     }
@@ -947,7 +947,7 @@
     // Setting the activeProperty to false pauses the sim and also enables optional support for playback back recorded
     // events (if playbackModeEnabledProperty) is true
     if ( this.activeProperty.value ) {
-      this.fuzzInputEvents(); // Handle Input fuzzing before stepping the sim because input events occur outside of sim steps.
+      fuzz && this.fuzzInputEvents(); // Handle Input fuzzing before stepping the sim because input events occur outside of sim steps.
 
       this.stepOneFrame();
     }

```

**Comment by zepumph** [comment]
Fixed with the above commit. @samreid will you please review this in concert with https://github.com/phetsims/phet-io-wrappers/issues/371.

**Comment by samreid** [comment]
That seems good.  I also considered running the fuzz after stepOneFrame (without a frameCounter check), but it's better to process input events first. Thanks!  Closing.
