### ISSUE TITLE
CT this.allTerms.getArrayCopy is not a function

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/equality-explorer#185]
Also in off-shoot sims.
```
equality-explorer : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650604398161%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: this.allTerms.getArrayCopy is not a function
TypeError: this.allTerms.getArrayCopy is not a function
at GD.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650604398161%7D&fuzz&memoryLimit=1000:886:1419532)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650604398161%7D&fuzz&memoryLimit=1000:886:1479382)
at Array.forEach
at $k.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650604398161%7D&fuzz&memoryLimit=1000:886:1479369)
at tL.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650604398161%7D&fuzz&memoryLimit=1000:886:1439436)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650604398161%7D&fuzz&memoryLimit=1000:886:1339767)
at il.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650604398161%7D&fuzz&memoryLimit=1000:886:552220)
at TI.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650604398161%7D&fuzz&memoryLimit=1000:886:1347597)
at TI.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650604398161%7D&fuzz&memoryLimit=1000:886:1347535)
at TI.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650604398161%7D&fuzz&memoryLimit=1000:886:1347265)
id: Bayes Chrome
Snapshot from 4/21/2022, 10:07:58 PM

----------------------------------

equality-explorer : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650622508807%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: this.allTerms.getArrayCopy is not a function
TypeError: this.allTerms.getArrayCopy is not a function
at GD.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650622508807%7D&fuzz&memoryLimit=1000:886:1419532)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650622508807%7D&fuzz&memoryLimit=1000:886:1479382)
at Array.forEach
at $k.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650622508807%7D&fuzz&memoryLimit=1000:886:1479369)
at tL.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650622508807%7D&fuzz&memoryLimit=1000:886:1439436)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650622508807%7D&fuzz&memoryLimit=1000:886:1339767)
at il.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650622508807%7D&fuzz&memoryLimit=1000:886:552220)
at TI.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650622508807%7D&fuzz&memoryLimit=1000:886:1347597)
at TI.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650622508807%7D&fuzz&memoryLimit=1000:886:1347535)
at TI.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/build/phet/equality-explorer_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650622508807%7D&fuzz&memoryLimit=1000:886:1347265)
id: Bayes Chrome
Snapshot from 4/21/2022, 10:07:58 PM

----------------------------------

equality-explorer : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/equality-explorer_en.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650608185462%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: this.allTerms.getArrayCopy is not a function
TypeError: this.allTerms.getArrayCopy is not a function
at getArrayCopy (TermCreator.js:254:39)
at step (EqualityExplorerScene.js:177:61)
at Array.forEach
at forEach (EqualityExplorerScene.js:177:25)
at step (EqualityExplorerModel.js:50:29)
at step (Sim.ts:458:21)
at apply (PhetioAction.ts:123:16)
at execute (Sim.ts:1021:30)
at stepSimulation (Sim.ts:1011:11)
at stepOneFrame (Sim.ts:986:11)
id: Bayes Chrome
Snapshot from 4/21/2022, 10:07:58 PM

----------------------------------

equality-explorer : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/equality-explorer_en.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650621307387%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught TypeError: this.allTerms.getArrayCopy is not a function
TypeError: this.allTerms.getArrayCopy is not a function
at getArrayCopy (TermCreator.js:254:39)
at step (EqualityExplorerScene.js:177:61)
at Array.forEach
at forEach (EqualityExplorerScene.js:177:25)
at step (EqualityExplorerModel.js:50:29)
at step (Sim.ts:458:21)
at apply (PhetioAction.ts:123:16)
at execute (Sim.ts:1021:30)
at stepSimulation (Sim.ts:1011:11)
at stepOneFrame (Sim.ts:986:11)
id: Bayes Chrome
Snapshot from 4/21/2022, 10:07:58 PM

----------------------------------

equality-explorer : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/equality-explorer_en.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650607207697%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: this.allTerms.getArrayCopy is not a function
TypeError: this.allTerms.getArrayCopy is not a function
at getArrayCopy (TermCreator.js:254:39)
at step (EqualityExplorerScene.js:177:61)
at Array.forEach
at forEach (EqualityExplorerScene.js:177:25)
at step (EqualityExplorerModel.js:50:29)
at step (Sim.ts:458:21)
at apply (PhetioAction.ts:123:16)
at execute (Sim.ts:1021:30)
at stepSimulation (Sim.ts:1011:11)
at stepOneFrame (Sim.ts:986:11)
id: Bayes Chrome
Snapshot from 4/21/2022, 10:07:58 PM

----------------------------------

equality-explorer : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/equality-explorer_en.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650608105242%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: this.allTerms.getArrayCopy is not a function
TypeError: this.allTerms.getArrayCopy is not a function
at getArrayCopy (TermCreator.js:254:39)
at step (EqualityExplorerScene.js:177:61)
at Array.forEach
at forEach (EqualityExplorerScene.js:177:25)
at step (EqualityExplorerModel.js:50:29)
at step (Sim.ts:458:21)
at apply (PhetioAction.ts:123:16)
at execute (Sim.ts:1021:30)
at stepSimulation (Sim.ts:1011:11)
at stepOneFrame (Sim.ts:986:11)
id: Bayes Chrome
Snapshot from 4/21/2022, 10:07:58 PM

----------------------------------

equality-explorer : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650600478229/equality-explorer/equality-explorer_en.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1650600478229%22%2C%22timestamp%22%3A1650610028442%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: this.allTerms.getArrayCopy is not a function
TypeError: this.allTerms.getArrayCopy is not a function
at getArrayCopy (TermCreator.js:254:39)
at step (EqualityExplorerScene.js:177:61)
at Array.forEach
at forEach (EqualityExplorerScene.js:177:25)
at step (EqualityExplorerModel.js:50:29)
at step (Sim.ts:458:21)
at apply (PhetioAction.ts:123:16)
at execute (Sim.ts:1021:30)
at stepSimulation (Sim.ts:1011:11)
at stepOneFrame (Sim.ts:986:11)
id: Bayes Chrome
Snapshot from 4/21/2022, 10:07:58 PM
```

**Comment by pixelzoom** [comment]
I don't see this error occuriring in CT any more.  I'm guessing that someone temporarily broke ObseverableArray, and that it's now fixed.  @KatieWoe can you please verify that that is the case?  If so, please close this issue.
