### ISSUE TITLE
CT: If maxWidth and preferredWidth are both non-null, maxWidth should NOT be smaller than the preferredWidth

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/equality-explorer#189]
Also in basics and two variables:
```
equality-explorer : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663758258345/equality-explorer/equality-explorer_en.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1663758258345%22%2C%22timestamp%22%3A1663766095894%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: If maxWidth and preferredWidth are both non-null, maxWidth should NOT be smaller than the preferredWidth. If that happens, it would trigger an infinite loop
Error: Assertion failed: If maxWidth and preferredWidth are both non-null, maxWidth should NOT be smaller than the preferredWidth. If that happens, it would trigger an infinite loop
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663758258345/assert/js/assert.js:28:13)
at assert (Node.ts:2809:14)
at auditMaxDimensions (WidthSizable.ts:201:44)
at listener (TinyEmitter.ts:95:8)
at emit (TinyProperty.ts:129:9)
at notifyListeners (TinyProperty.ts:77:11)
at set (TinyProperty.ts:63:9)
at (WidthSizable.ts:120:6)
at (LayoutProxy.ts:438:4)
at (Checkbox.ts:323:6)
id: Bayes Puppeteer
Snapshot from 9/21/2022, 5:04:18 AM

----------------------------------

equality-explorer : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663758258345/equality-explorer/equality-explorer_en.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1663758258345%22%2C%22timestamp%22%3A1663773105022%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: If maxWidth and preferredWidth are both non-null, maxWidth should NOT be smaller than the preferredWidth. If that happens, it would trigger an infinite loop
Error: Assertion failed: If maxWidth and preferredWidth are both non-null, maxWidth should NOT be smaller than the preferredWidth. If that happens, it would trigger an infinite loop
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663758258345/assert/js/assert.js:28:13)
at assert (Node.ts:2809:14)
at auditMaxDimensions (WidthSizable.ts:201:44)
at listener (TinyEmitter.ts:95:8)
at emit (TinyProperty.ts:129:9)
at notifyListeners (TinyProperty.ts:77:11)
at set (TinyProperty.ts:63:9)
at (WidthSizable.ts:120:6)
at (LayoutProxy.ts:438:4)
at (Checkbox.ts:323:6)
id: Bayes Puppeteer
Snapshot from 9/21/2022, 5:04:18 AM
```

**Comment by pixelzoom** [comment]
I suspect that CT may have been working with an incomplete checkout, since I've been doing a lot of TypeScript conversion in #186. I can't reproduce this locally.  And the most recent run of CT does not show this problem.

It's also not clear to me why CT is doing a fuzz test for `stringText=xss`.  See https://github.com/phetsims/aqua/issues/159.

So I'm going to wait a bit before investigating this further.

**Comment by pixelzoom** [comment]
CT is no longer reporting this problem.  So I suspect is was working with an incomplete checkout of TypeScript changes. 

Closing. Will reopen if it reoccurs.
