### ISSUE TITLE
CT: Assertion failure in CombineTermsDragListener.ts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#190]
Likely caused by #186 (convert to TypeScript)

```
equality-explorer : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664196819703/equality-explorer/equality-explorer_en.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1664196819703%22%2C%22timestamp%22%3A1664204029347%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664196819703/assert/js/assert.js:28:13)
at assert (CombineTermsDragListener.ts:312:22)
at animationCompletedCallback (EqualityExplorerMovable.ts:183:48)
at step (TermCreator.js:266:26)
at step (EqualityExplorerScene.ts:210:61)
at Array.forEach
at forEach (EqualityExplorerScene.ts:210:25)
at step (EqualityExplorerModel.ts:55:29)
at step (Sim.ts:432:21)
at apply (PhetioAction.ts:124:16)
id: Bayes Puppeteer
Snapshot from 9/26/2022, 6:53:39 AM
```

**Comment by pixelzoom** [comment]
This is failing where I relocated one line of code -- assignment of `const sumToZeroParent`.   In the above commit, I've restored the assignment to its original location.  I can't tell why it should matter, but we'll see if it resolves the issue.

**Comment by pixelzoom** [comment]
> I can't tell why it should matter, but we'll see if it resolves the issue.

I figured out why it matters, documented in the above commit:

```
    // This must be done here. If this.term is disposed later in this method, this.termNode will also be disposed,
    // and will not have a parent.
    const sumToZeroParent = this.termNode.getParent()!;
```

**Comment by pixelzoom** [comment]
CT is happy. Closing.
