### ISSUE TITLE
support ?shuffleListeners

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#205]
Related to https://github.com/phetsims/axon/issues/215, where @zepumph added a `shuffleListeners` test to CT.

Short-term work is to investigate where this is failing, and add `hasListenerOrderDependencies: true` with a TODO comment that references this issue.  Long-term work is to eliminate the order dependency, if feasible and cost-effective.

```
equality-explorer : fuzz : unbuilt : shuffleListeners
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1679397130435/equality-explorer/equality-explorer_en.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22shuffleListeners%22%5D%2C%22snapshotName%22%3A%22snapshot-1679397130435%22%2C%22timestamp%22%3A1679402863087%7D&brand=phet&ea&fuzz&shuffleListeners&memoryLimit=1000
Query: brand=phet&ea&fuzz&shuffleListeners&memoryLimit=1000
Uncaught Error: Assertion failed: unexpected operand type: VariableTerm: 1/1 Variable: symbol=‪x‬ value=-4
Error: Assertion failed: unexpected operand type: VariableTerm: 1/1 Variable: symbol=‪x‬ value=-4
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1679397130435/assert/js/assert.js:28:13)
at assert (UniversalOperationControl.ts:210:20)
at callback (Multilink.ts:111:10)
at listener (TinyEmitter.ts:102:8)
at emit (ReadOnlyProperty.ts:312:22)
at _notifyListeners (ReadOnlyProperty.ts:263:13)
at unguardedSet (ReadOnlyProperty.ts:247:11)
at set (Property.ts:65:10)
at set (RectangularRadioButton.ts:139:50)
at listener (TinyEmitter.ts:102:8)
id: Bayes Puppeteer
Snapshot from 3/21/2023, 7:12:10 AM
```

**Comment by zepumph** [comment]
Taking a look now

**Comment by zepumph** [comment]
I'm pretty sure that this is the right Property, but CT will tell us for sure. If we still run into it, I will try adding the flag to `operandProperty` next.

**Comment by zepumph** [comment]
Looking clear on CT this morning. Not closing though
