### ISSUE TITLE
Assertion failed: cannot be disposed twice

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#88]
Investigate this CT fuzz error, which happens rarely:

equality-explorer : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: cannot be disposed twice
Error: Assertion failed: cannot be disposed twice
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1525578098739/assert/js/assert.js:22:13)
    at BooleanProperty.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1525578098739/axon/js/Property.js?bust=1525580170023:407:19)
    at VariableTerm.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1525578098739/equality-explorer/js/common/model/Term.js?bust=1525580170023:93:29)
    at VariableTerm.animationCompletedCallback (https://bayes.colorado.edu/continuous-testing/snapshot-1525578098739/equality-explorer/js/common/view/TermDragListener.js?bust=1525580170023:417:33)
    at VariableTerm.step (https://bayes.colorado.edu/continuous-testing/snapshot-1525578098739/equality-explorer/js/common/model/EqualityExplorerMovable.js?bust=1525580170023:176:51)
    at VariableTermCreator.step (https://bayes.colorado.edu/continuous-testing/snapshot-1525578098739/equality-explorer/js/common/model/TermCreator.js?bust=1525580170023:254:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1525578098739/equality-explorer/js/common/model/Scene.js?bust=1525580170023:201:21
    at Array.forEach (<anonymous>)
    at VariablesScene.step (https://bayes.colorado.edu/continuous-testing/snapshot-1525578098739/equality-explorer/js/common/model/Scene.js?bust=1525580170023:200:28)
    at VariablesModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1525578098739/equality-explorer/js/common/model/EqualityExplorerModel.js?bust=1525580170023:60:32)
Approximately 5/5/2018, 9:41:38 PM

**Comment by pixelzoom** [comment]
The problem is at line 417 of `animateToToolbox` in TermDragListener.  `dispose` must have been previously called for `equivalentTerm`.

```js
          if ( self.equivalentTerm ) {
417         self.equivalentTerm.dispose();
            self.equivalentTerm = null;
            self.detachOppositeTerms();
          }
```

... and it's failing on line 93 of Term `dispose`:

```js
    dispose: function() {
93    this.pickableProperty.dispose();
```

The assertion is on line 407 of Property:

```js
      dispose: function() {

407     assert && assert( !this.isDisposed, 'cannot be disposed twice' );
```

**Comment by pixelzoom** [comment]
Hmmm.... I don't see how `dispose` could have been called twice for `equivalentTerm`.  It's private (verified) to TermDragListener, and everywhere that `dispose` is called, it's immediately set to `null`, e.g.:

```js
self.equivalentTerm.dispose();
self.equivalentTerm = null;
```

So any attempt to call `dispose` again would have failed with `"Cannot read property 'dispose' of null"`.

**Comment by pixelzoom** [comment]
Steps to reproduce:

1. Run with `?ea&maxInteger=1`
2. Got to Operations screen
3. Drag an 'x' from left toolbox to left plate
4. Turn on lock
5. Drag an 'x' from right toolbox to right plate
5. Drag another 'x' from right toolbox to right plate

This is not specific to 'x' terms, also reproducible with '1' terms.

**Comment by pixelzoom** [comment]
This was fixed by the above commit, related to the lock feature #19.   When maxInteger was exceeded, all terms not on the scale were being deleted, but the drag listener code continued to run for the equivalentTerm side of the scale.  Since equivalentTerm was off the scale at that point, this resulted in 2 calls to `dispose` for equivalentTerm.

Closing.

**Comment by pixelzoom** [comment]
Reopening.  This still occurs in CT (rarely, and with a different stack trace) so should be revisited.   It won't cause problems in a production version (assertions disabled), so it's not blocking for 1.0 publication. 

equality-explorer-two-variables : fuzz : require.js : run
Uncaught Error: Assertion failed: cannot be disposed twice
Error: Assertion failed: cannot be disposed twice
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1529213474149/assert/js/assert.js:22:13)
    at BooleanProperty.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1529213474149/axon/js/Property.js?bust=1529233257188:407:19)
    at VariableTerm.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1529213474149/equality-explorer/js/common/model/Term.js?bust=1529233257188:93:29)
    at VariableTermCreator.disposeTerms (https://bayes.colorado.edu/continuous-testing/snapshot-1529213474149/equality-explorer/js/common/model/TermCreator.js?bust=1529233257188:469:20)
    at VariableTermCreator.disposeAllTerms (https://bayes.colorado.edu/continuous-testing/snapshot-1529213474149/equality-explorer/js/common/model/TermCreator.js?bust=1529233257188:439:12)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1529213474149/equality-explorer/js/common/model/EqualityExplorerScene.js?bust=1529233257188:188:21
    at Array.forEach (<anonymous>)
    at TwoVariablesScene.disposeAllTerms (https://bayes.colorado.edu/continuous-testing/snapshot-1529213474149/equality-explorer/js/common/model/EqualityExplorerScene.js?bust=1529233257188:187:28)
    at TwoVariablesScene.reset (https://bayes.colorado.edu/continuous-testing/snapshot-1529213474149/equality-explorer/js/common/model/EqualityExplorerScene.js?bust=1529233257188:169:12)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1529213474149/equality-explorer/js/common/model/EqualityExplorerModel.js?bust=1529233257188:48:15
Approximately 6/16/2018, 11:31:14 PM

**Comment by pixelzoom** [comment]
I could change Term `dispose` to this:

```js
dispose: function() {
  if ( !this.disposed ) {
    ...
  }
}
```

... but that hides the problem without addressing it.

**Comment by pixelzoom** [comment]
For an error of the form "equality-explorer : fuzz : require.js-canvas : run", CT is using query parameters `&ea&fuzzMouse&fuzzTouch`.  See continuous-server.js line 640.

**Comment by pixelzoom** [comment]
Apparently the `fuzzTouch` query parameter is important. Running with `&ea&fuzzMouse&fuzzTouch` in requirejs mode, I reproduced the failure. 

Here's the stack trace, which is different from the previous 2.  In this case, it's failing as a result of the lock state changing, which disposes of all terms that are not on the plate.

> window.assertions.assertFunction (assert.js:22)
dispose (Property.js?bust=1530905624500:412)
dispose (Term.js?bust=1530905624500:93)
disposeTerms (TermCreator.js?bust=1530905624500:469)
disposeTermsNotOnPlate (TermCreator.js?bust=1530905624500:458)
(anonymous) (TermCreator.js?bust=1530905624500:129)
emit2 (Emitter.js?bust=1530905624500:180)
_notifyListeners (Property.js?bust=1530905624500:287)
setValueAndNotifyListeners (Property.js?bust=1530905624500:274)
set (Property.js?bust=1530905624500:217)
set value (Property.js?bust=1530905624500:316)
(anonymous) (EqualityExplorerScene.js?bust=1530905624500:124)
emit2 (Emitter.js?bust=1530905624500:180)
_notifyListeners (Property.js?bust=1530905624500:287)
setValueAndNotifyListeners (Property.js?bust=1530905624500:274)
set (Property.js?bust=1530905624500:217)
reset (Property.js?bust=1530905624500:309)
reset (EqualityExplorerScene.js?bust=1530905624500:166)
(anonymous) (EqualityExplorerModel.js?bust=1530905624500:48)
reset (EqualityExplorerModel.js?bust=1530905624500:47)
listener (EqualityExplorerScreenView.js?bust=1530905624500:48)
emit (Emitter.js?bust=1530905624500:134)
fire (PushButtonModel.js?bust=1530905624500:146)
(anonymous) (PushButtonModel.js?bust=1530905624500:83)
emit2 (Emitter.js?bust=1530905624500:180)
_notifyListeners (Property.js?bust=1530905624500:287)
setValueAndNotifyListeners (Property.js?bust=1530905624500:274)
set (Property.js?bust=1530905624500:217)
set value (Property.js?bust=1530905624500:316)
release (PressListener.js?bust=1530905624500:469)
up (PressListener.js?bust=1530905624500:203)
dispatchToListeners (Input.js?bust=1530905624500:1352)
dispatchEvent (Input.js?bust=1530905624500:1308)
upEvent (Input.js?bust=1530905624500:1071)
mouseUp (Input.js?bust=1530905624500:511)
mouseToggle (InputFuzzer.js?bust=1530905624500:279)
InputFuzzer.mouseToggleAction (InputFuzzer.js?bust=1530905624500:46)
fuzzEvents (InputFuzzer.js?bust=1530905624500:114)
stepSimulation (Sim.js?bust=1530905624500:804)
stepOneFrame (Sim.js?bust=1530905624500:769)
runAnimationLoop (Sim.js?bust=1530905624500:752)
requestAnimationFrame (async)

Here's what the screen looked like:

![screenshot_687](https://user-images.githubusercontent.com/3046552/42396995-6108eee8-8121-11e8-924d-47a7a467100e.png)

**Comment by pixelzoom** [comment]
I temporarily added an assertion to TermCreator `disposeTerms`:

`assert && assert( !terms[ i ].disposed, 'term was already disposed: ' + terms[ i ].toString() );`

Reproduced the error with `&ea&fuzzMouse&fuzzTouch`.  This time the failure was triggered by pressing the "clear scale" button. 

Stack trace:

> Assertion failed: term was already disposed: VariableTerm: 1/1 Variable: ‪y‬=4
window.assertions.assertFunction (assert.js:22)
disposeTerms (TermCreator.js?bust=1530907423815:469)
disposeTermsOnPlate (TermCreator.js?bust=1530907423815:449)
(anonymous) (BalanceScale.js?bust=1530907423815:188)
clear (BalanceScale.js?bust=1530907423815:187)
ClearScaleButton.options.listener (ClearScaleButton.js?bust=1530907423815:33)

Screenshot:

![screenshot_688](https://user-images.githubusercontent.com/3046552/42398663-f57d5d6a-8127-11e8-96f0-236b6b0d3a45.png)

**Comment by pixelzoom** [comment]
After spending way too much time on this, I was seriously considering the workaround in https://github.com/phetsims/equality-explorer/issues/88#issuecomment-403116845, i.e. in `Term`:

```js
    /**
     * @public
     * @override
     */
    dispose: function() {

      // Workaround for a multi-touch situation that results in a Term being disposed twice.
      // This occurs (rarely) in fuzz testing, but could not be reproduced manually.
      // See https://github.com/phetsims/equality-explorer/issues/88
      if ( !this.disposed ) {
        this.pickableProperty.dispose();
        this.onPlateProperty.dispose();
        this.shadowVisibleProperty.dispose();
        this.haloVisibleProperty.dispose();
        EqualityExplorerMovable.prototype.dispose.call( this );
      }
      else {
        phet.log && phet.log( 'WARNING: ignoring attempt to dispose of Term twice: ' + this.toString() );
      }
    },
```

But once this warning occurs (which can take a long while), then it occurs constantly.  And that might be indicative of a memory leak, perhaps TermCreator keeping a reference to a Term that was previously disposed.  

So... Back to the drawing board.

**Comment by pixelzoom** [comment]
I added (but did not commit) a counter to Term to count the number of times that `dispose` is called.  The idea was to verify that the same instance of Term has its `dispose` called over and over, versus lots of instances that have their `dispose` called only twice.   I ran for a long time with `&ea&fuzzMouse&fuzzTouch`, but did not reproduced.  Will try again later.

**Comment by pixelzoom** [comment]
This assertion failure happened in CT...

On 7/5:

> equality-explorer-two-variables : xss-fuzz : run
Uncaught Error: Assertion failed: cannot be disposed twice
Error: Assertion failed: cannot be disposed twice
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1530902597009/assert/js/assert.js:22:13)
    at BooleanProperty.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1530902597009/axon/js/Property.js?bust=1530904352556:412:19)
    at VariableTerm.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1530902597009/equality-explorer/js/common/model/Term.js?bust=1530904352556:93:29)
    at VariableTerm.animationCompletedCallback (https://bayes.colorado.edu/continuous-testing/snapshot-1530902597009/equality-explorer/js/common/view/SeparateTermsDragListener.js?bust=1530904352556:216:34)
    at VariableTerm.step (https://bayes.colorado.edu/continuous-testing/snapshot-1530902597009/equality-explorer/js/common/model/EqualityExplorerMovable.js?bust=1530904352556:177:51)
    at VariableTermCreator.step (https://bayes.colorado.edu/continuous-testing/snapshot-1530902597009/equality-explorer/js/common/model/TermCreator.js?bust=1530904352556:264:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1530902597009/equality-explorer/js/common/model/EqualityExplorerScene.js?bust=1530904352556:211:21
    at Array.forEach (<anonymous>)
    at TwoVariablesScene.step (https://bayes.colorado.edu/continuous-testing/snapshot-1530902597009/equality-explorer/js/common/model/EqualityExplorerScene.js?bust=1530904352556:210:28)
    at TwoVariablesModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1530902597009/equality-explorer/js/common/model/EqualityExplorerModel.js?bust=1530904352556:61:32)
Approximately 7/6/2018, 12:43:17 PM

On 7/8:

> equality-explorer-two-variables : xss-fuzz : run
Uncaught Error: Assertion failed: cannot be disposed twice
Error: Assertion failed: cannot be disposed twice
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1530992388758/assert/js/assert.js:22:13)
    at BooleanProperty.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1530992388758/axon/js/Property.js?bust=1530999975899:412:19)
    at VariableTerm.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1530992388758/equality-explorer/js/common/model/Term.js?bust=1530999975899:93:29)
    at VariableTermCreator.disposeTerms (https://bayes.colorado.edu/continuous-testing/snapshot-1530992388758/equality-explorer/js/common/model/TermCreator.js?bust=1530999975899:469:20)
    at VariableTermCreator.disposeAllTerms (https://bayes.colorado.edu/continuous-testing/snapshot-1530992388758/equality-explorer/js/common/model/TermCreator.js?bust=1530999975899:439:12)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1530992388758/equality-explorer/js/common/model/EqualityExplorerScene.js?bust=1530999975899:188:21
    at Array.forEach (<anonymous>)
    at TwoVariablesScene.disposeAllTerms (https://bayes.colorado.edu/continuous-testing/snapshot-1530992388758/equality-explorer/js/common/model/EqualityExplorerScene.js?bust=1530999975899:187:28)
    at TwoVariablesScene.reset (https://bayes.colorado.edu/continuous-testing/snapshot-1530992388758/equality-explorer/js/common/model/EqualityExplorerScene.js?bust=1530999975899:169:12)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1530992388758/equality-explorer/js/common/model/EqualityExplorerModel.js?bust=1530999975899:48:15
Approximately 7/7/2018, 1:39:48 PM

**Comment by pixelzoom** [comment]
Using the counter mentioned in https://github.com/phetsims/equality-explorer/issues/88#issuecomment-403163140... I verified that once a Term is disposed of more than once, it will continue to be disposed of over and over (e.g. each time a scene is reset).    So this issue also represents a slight memory leak, since a Term that has been disposed should have been removed from TermCreator's `allTerms` and/or `termsOnPlate` arrays.

**Comment by pixelzoom** [comment]
Fixed a couple of things in the above commits, including getting rid of the `detachRelatedTerms` function in TermDragListener.   It survived 5 hours of `&ea&fuzzMouse&fuzzTouch` without failing.  I'll leave this open to see if anything shows up in CT.

**Comment by pixelzoom** [comment]
And the problem is still present for the `animationCompletedCallback` case :( 

From 7/9/2018 CT:

> equality-explorer-two-variables : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: cannot be disposed twice
Error: Assertion failed: cannot be disposed twice
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1531149676751/assert/js/assert.js:22:13)
    at BooleanProperty.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1531149676751/axon/js/Property.js?bust=1531151332359:412:19)
    at ConstantTerm.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1531149676751/equality-explorer/js/common/model/Term.js?bust=1531151332359:93:29)
    at ConstantTerm.animationCompletedCallback (https://bayes.colorado.edu/continuous-testing/snapshot-1531149676751/equality-explorer/js/common/view/TermDragListener.js?bust=1531151332359:299:33)
    at ConstantTerm.step (https://bayes.colorado.edu/continuous-testing/snapshot-1531149676751/equality-explorer/js/common/model/EqualityExplorerMovable.js?bust=1531151332359:178:51)
    at ConstantTermCreator.step (https://bayes.colorado.edu/continuous-testing/snapshot-1531149676751/equality-explorer/js/common/model/TermCreator.js?bust=1531151332359:264:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1531149676751/equality-explorer/js/common/model/EqualityExplorerScene.js?bust=1531151332359:211:21
    at Array.forEach (<anonymous>)
    at TwoVariablesScene.step (https://bayes.colorado.edu/continuous-testing/snapshot-1531149676751/equality-explorer/js/common/model/EqualityExplorerScene.js?bust=1531151332359:210:28)
    at TwoVariablesModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1531149676751/equality-explorer/js/common/model/EqualityExplorerModel.js?bust=1531151332359:61:32)
Approximately 7/9/2018, 9:21:16 AM

**Comment by pixelzoom** [comment]
To summarize, there are 5 scenarios where this issue has manifested:

1. `TermDragListener.animateToToolbox`, in the `animationCompletedCallback`
2. `SeparateTermsDragListener.animateToPlate`, in the `animationCompletedCallback`
3. `TermCreator.disposeAllTerms`, as the result of pressing the ‘Reset All’ button
4. `TermCreator.disposeTermsOnPlate`, as the result of pressing the ‘clear scale’ button.
5. `TermCreator.disposeTermsNotOnPlate`, as the result of changing the state of the lock button

1 & 2 could probably be ignored without negative impacts on the production version.  At least one of these (1) is still manifesting in CT.  And it may be the case that `animationCompletedCallback` is already scheduled to be called when something else disposes of the related terms. A reasonable workaround (solution?) would be to check `term.disposed` before calling `term.dispose` in the drag listeners. 

3-5 indicate that a disposed term is still in the list of managed terms, and is therefore a memory leak.  Since this occurs infrequently, the leak has negligible practical impact.  And after making the changes in https://github.com/phetsims/equality-explorer/issues/88#issuecomment-403351332, these have not manifested in CT.   A workaround would be to check `term.disposed` in `TermCreator.disposeTerms`, and clean up the aberrant term (remove from lists, remove from plate, etc).

For 1.0 release, it's probably OK to "do nothing" about this issue, since it won't crash the sim and has negligible impact on memory.  But given how complicated the user interaction is in this sim, if it doesn't get resolved now, it's unlikely to ever get resolved.

**Comment by pixelzoom** [comment]
I applied workaround for all of the scenarios, see above commits.  I'll give this a couple of days to verify in CT.

In the case of scenarios 3-5, if you run with `?log` and a term is encountered that has already been disposed, the term will be cleaned up, and you'll see a red log message in the console, e.g.:

![screenshot_691](https://user-images.githubusercontent.com/3046552/42539982-04d9cdb8-845a-11e8-97f2-b1319f80fba3.png)

**Comment by pixelzoom** [comment]
Running equality-explorer-two-variables with `?ea&log&fuzzMouse&fuzzTouch`, I identified a 6th scenario.

6. `TermCreator.putTermOnPlate`, where the term has already been disposed

Stack trace:

> window.assertions.assertFunction (assert.js:22)
manageTerm (TermCreator.js?bust=1531259608058:300)
putTermOnPlate (TermCreator.js?bust=1531259608058:374)
animationCompletedCallback (SeparateTermsDragListener.js?bust=1531259608058:207)
step (EqualityExplorerMovable.js?bust=1531259608058:178)
step (TermCreator.js?bust=1531259608058:265)
(anonymous) (EqualityExplorerScene.js?bust=1531259608058:211)
step (EqualityExplorerScene.js?bust=1531259608058:210)
step (EqualityExplorerModel.js?bust=1531259608058:61)
stepSimulation (Sim.js?bust=1531259608058:836)
stepOneFrame (Sim.js?bust=1531259608058:769)
runAnimationLoop (Sim.js?bust=1531259608058:752)
requestAnimationFrame (async)


This again occurs when called from `animationCompletedCallback`,  `SeparateTermsDragListener` line 207:

`self.equivalentTermCreator.putTermOnPlate( self.equivalentTerm, equivalentCell );`

So I suspect that the callback is being schedule, then something happens to dispose `equivalentTerm`, then the callback executes.

**Comment by pixelzoom** [comment]
OK, this makes sense to me now.  A drag listener has `this.term` and (optionally) `this.equivalentTerm` and `this.inverseTerm`.   If term has been disposed of, its step function will not be called, and `animationCompletedCallback` will not be called.  But that doesn't take into account whether equivalentTerm or inverseTerm have been disposed.   So in `animationCompletedCallback`, I need to provide logic for what to do if they have been disposed.

**Comment by pixelzoom** [comment]
Pushed a fix for scenario 6, and a fix for a bug that crept in on the Operations screen.

**Comment by pixelzoom** [comment]
I ran equality-explorer and equality-explorer-two-variables for 10+ hours with `?ea&log&fuzzMouse&fuzzTouch` and did not encounter this problem.   And nothing has shown up in CT since yesterday's fixes.   So (fingers crossed) I'm going to close this issue.
