### ISSUE TITLE
Assertion failed: attempt to step disposed movable

### ISSUE THREAD

**Issue by phet-steele** [phetsims/equality-explorer#94]
1. Numbers or Variables screen (start with empty plates just to eliminate extraneous variables).
2. Pick a plate and stack a term and its inverse:
<img width="967" alt="screen shot 2018-05-08 at 9 59 08 am" src="https://user-images.githubusercontent.com/5863899/39768433-80ad7998-52a6-11e8-9a3e-7d306711c94b.png">

3. LOCK!
4. Rapidly click the bottom term in your stack to get the below error. I have better luck when clicking towards the bottom-center of the bottom term. If your stack combines to zero, use the stack on the opposite plate instead (should be there since you locked).

```
Uncaught Error: Assertion failed: attempt to step disposed movable
    at window.assertions.assertFunction (assert.js:22)
    at ConstantTerm.step (EqualityExplorerMovable.js?bust=1525794442027:154)
    at ConstantTermCreator.step (TermCreator.js?bust=1525794442027:254)
    at Scene.js?bust=1525794442027:201
    at Array.forEach (<anonymous>)
    at NumbersScene.step (Scene.js?bust=1525794442027:200)
    at NumbersModel.step (EqualityExplorerModel.js?bust=1525794442027:60)
    at Sim.stepSimulation (Sim.js?bust=1525794442027:863)
    at Sim.stepOneFrame (Sim.js?bust=1525794442027:801)
    at Sim.runAnimationLoop (Sim.js?bust=1525794442027:784)
```

Seen on macOS 10.13.4 Chrome with master at https://github.com/phetsims/equality-explorer/commit/03193750226420c751a218b5f1d0c33be82df58a. For #91.

**Comment by pixelzoom** [comment]
Reproduced, will investigate. 

Verified that the failure occurs only when a term and its inverse are stacked (e.g. 1 and -1, x and -x).  If two non-inverse terms are stacked (i.e. 1 and 1, -1 and -1, x and x, -x and -x), there is no failure.

**Comment by phet-steele** [comment]
@pixelzoom I have a better idea of what is happening.

Just after locking in step 3, we have it so that picking up one of the terms, say "-1", will create two new terms on the opposite plate, a "-1" and "1". Then, when releasing the dragged "-1", those two terms on the opposite plate go away. This phenomenon:

![eqex08](https://user-images.githubusercontent.com/5863899/39784169-bf5f93a0-52d4-11e8-91f8-cc303ceb93c1.gif)

BUT, you can totally break this with multitouch/fast clicking by dragging one of the two new terms (***via lock, as in take the "1" from the left plate above, not the plate the new terms were created on***). Then, when releasing the "-1", it will try to do the phenomenon above and destroy the two terms opposite it, yet the user is still interacting with one of those.

**Comment by pixelzoom** [comment]
@phet-steele Thanks for the additional info.

**Comment by pixelzoom** [comment]
Looks like this started showing up in CT on 5/8/2018 @ 1:35:09 PM.

**Comment by pixelzoom** [comment]
In CT, it's showing up consistently in the Operations screen, with both constant and variable terms. 

Examples:

> equality-explorer : fuzz : require.js : run
Uncaught Error: Assertion failed: attempt to step disposed movable
Error: Assertion failed: attempt to step disposed movable
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1525835433331/assert/js/assert.js:22:13)
    at ConstantTerm.step (https://bayes.colorado.edu/continuous-testing/snapshot-1525835433331/equality-explorer/js/common/model/EqualityExplorerMovable.js?bust=1525862843292:154:17)
    at ConstantTermCreator.step (https://bayes.colorado.edu/continuous-testing/snapshot-1525835433331/equality-explorer/js/common/model/TermCreator.js?bust=1525862843292:257:27)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1525835433331/equality-explorer/js/common/model/Scene.js?bust=1525862843292:205:21
    at Array.forEach (<anonymous>)
    at OperationsScene.step (https://bayes.colorado.edu/continuous-testing/snapshot-1525835433331/equality-explorer/js/common/model/Scene.js?bust=1525862843292:204:28)
    at OperationsModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1525835433331/equality-explorer/js/common/model/EqualityExplorerModel.js?bust=1525862843292:60:32)
    at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1525835433331/joist/js/Sim.js?bust=1525862843292:863:22)
    at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/snapshot-1525835433331/joist/js/Sim.js?bust=1525862843292:801:14)
    at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/snapshot-1525835433331/joist/js/Sim.js?bust=1525862843292:784:14)
Approximately 5/8/2018, 9:10:33 PM

> equality-explorer : fuzz : require.js : run
Uncaught Error: Assertion failed: attempt to step disposed movable
Error: Assertion failed: attempt to step disposed movable
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1525816473472/assert/js/assert.js:22:13)
    at VariableTerm.step (https://bayes.colorado.edu/continuous-testing/snapshot-1525816473472/equality-explorer/js/common/model/EqualityExplorerMovable.js?bust=1525820068402:154:17)
    at VariableTermCreator.step (https://bayes.colorado.edu/continuous-testing/snapshot-1525816473472/equality-explorer/js/common/model/TermCreator.js?bust=1525820068402:257:27)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1525816473472/equality-explorer/js/common/model/Scene.js?bust=1525820068402:201:21
    at Array.forEach (<anonymous>)
    at OperationsScene.step (https://bayes.colorado.edu/continuous-testing/snapshot-1525816473472/equality-explorer/js/common/model/Scene.js?bust=1525820068402:200:28)
    at OperationsModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1525816473472/equality-explorer/js/common/model/EqualityExplorerModel.js?bust=1525820068402:60:32)
    at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1525816473472/joist/js/Sim.js?bust=1525820068402:863:22)
    at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/snapshot-1525816473472/joist/js/Sim.js?bust=1525820068402:801:14)
    at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/snapshot-1525816473472/joist/js/Sim.js?bust=1525820068402:784:14)
Approximately 5/8/2018, 3:54:33 PM

**Comment by pixelzoom** [comment]
@phet-steele In https://github.com/phetsims/equality-explorer/issues/94#issue-321249302, you said:

> 1. Numbers or Operations screen (start with empty plates just to eliminate extraneous variables).
> 2. Pick a plate and stack a term and its inverse:

Did you mean "Numbers or _Variables_ screen"?  Because it's impossible to do step 2 in Operations screen.

**Comment by phet-steele** [comment]
> Looks like this started showing up in CT on 5/8/2018 @ 1:35:09 PM.

I found it 3.5 hours before bayes could, take that you silly machine!

**Comment by phet-steele** [comment]
> Did you mean "Numbers or Variables screen"? Because it's impossible to do step 2 in Operations screen.

Yup definitely, typo that I will edit.

**Comment by pixelzoom** [comment]
CT is finding this problem in the Operations screen, but I have not been able to manually reproduce the steps required to make it happen.

**Comment by phet-steele** [comment]
> CT is finding this problem in the Operations screen, but I have not been able to manually reproduce the steps required to make it happen.

Sounds like a fun challenge. I'm on it!

**Comment by pixelzoom** [comment]
> I found it 3.5 hours before bayes could, take that you silly machine!

Hmmm... Perhaps CT noticed that @phet-steele found the problem in the other 2 screens, "realized" that the report was incomplete, and decided to point out the omission to the silly human :)

**Comment by phet-steele** [comment]
> CT is finding this problem in the Operations screen, but I have not been able to manually reproduce the steps required to make it happen.
> 
> Sounds like a fun challenge. I'm on it!

1. Used `?speed=0.1` to help me. Start with empty plates.
2. Place an "x" on one plate.
3. LOCK!
4. Grab that "x" and move it up off the plate. This will create a "-x" on the opposite plate.
5. Release the "x", and as it is floating back down, grab the "-x" and hold it.

Once the "x" touches down, while you are still holding the "-x", the assertion is hit.

**Comment by phet-steele** [comment]
> Hmmm... Perhaps CT noticed that @phet-steele found the problem in the other 2 screens, "realized" that the report was incomplete, and decided to point out the omission to the silly human :)

To my credit, if the "omission" was the Operations screen, I did include it as a typo...so ha!

**Comment by pixelzoom** [comment]
Another variation to reproduce it on Operations screen. This variation is important because it does not involve the lock feature.

1. run with `?speed=0.1`
2. put 'x' on right plate
4. drag 'x' from right toolbox, release above right plate
5. while 'x' is animating to right plate, click 'x' on right plate rapidly/repeatedly 
6. after animating 'x' reaches right plate, stop clicking, and the assertion is hit

**Comment by pixelzoom** [comment]
When doing `step`, we're iterating over an array of terms.  We necessarily make a copy of the array, since stepping may modify the array and would be a "concurrent modification" problem.  Stepping a term may result in some other term being disposed, but still in the array.  So while we iterate over the array, we need to skip terms that have been disposed.   Implemented in the above commit.

@phet-steele (and CT :) please verify.

**Comment by pixelzoom** [comment]
CT appears to be happy.

**Comment by phet-steele** [comment]
@pixelzoom if I repeat the original steps after pulling https://github.com/phetsims/equality-explorer/commit/39bb822629cefe6b9372e6db6251a38a4d82da21, I get a dead term on the opposite plate (can't interact with it, but it is still recognized by the sim [has weight on the scale]). No assertion is thrown.

Looks like the "double click" has to successfully combine the two terms? Didn't look too hard into this yet.

![eqex09](https://user-images.githubusercontent.com/5863899/39827012-dc26225c-5373-11e8-9c47-4248fb65855b.gif)

**Comment by phet-steele** [comment]
Removing the automated testing label because I found it! 😠

**Comment by pixelzoom** [comment]
Reproduced, will investigate.

**Comment by phet-steele** [comment]
Removing that dead term via locked dragging throws an assertion for trying to dispose twice....so that dead term was likely "disposed" at some point.

**Comment by pixelzoom** [comment]
Pushing the reset button (either Reset All or on the scale) also results in `Assertion failed: cannot be disposed twice`.   So yes, the dead term was definitely disposed at some point.

**Comment by pixelzoom** [comment]
@phet-steele I can't seem to reproduce https://github.com/phetsims/equality-explorer/issues/94#issuecomment-387797937 anymore.  There have been significant changes to drag handling over the past couple of weeks, so this might have been fixed indirectly (I hate when that happens).  Can you please verify?

**Comment by phet-steele** [comment]
I can't reproduce anymore either. Tentatively closing. I guess....good job?
